#ifndef DEFINICOES_SISTEMA_H_INCLUDED
#define DEFINICOES_SISTEMA_H_INCLUDED

#define true  1
#define false 0

#define PRODUTO_1 1
#define PRODUTO_2 2
#define PRODUTO_3 3
#define PRODUTO_4 4
#define PRODUTO_5 5
#define PRODUTO_6 6
#define PRODUTO_7 7
#define PRODUTO_8 8
#define PRODUTO_9 9

#define PRECO_PRODUTO_1 0.50
#define PRECO_PRODUTO_2 1.50
#define PRECO_PRODUTO_3 0.05
#define PRECO_PRODUTO_4 0.10
#define PRECO_PRODUTO_5 0.30
#define PRECO_PRODUTO_6 2.50
#define PRECO_PRODUTO_7 0.50
#define PRECO_PRODUTO_8 0.80
#define PRECO_PRODUTO_9 2.00


#define NUM_ESTADOS 7
#define NUM_EVENTOS 14

// ESTADOS
#define IDLE 0
#define COLOCANDO_MOEDAS 1  
#define ESPERANDO_USUARIO_DECIDIR 2
#define VERIFICANDO_POSSIBILIDADE_COMPRA 3
#define DERRUBANDO_PRODUTO 4
#define VERIFICANDO_SENHA_MANUTENCAO 5
#define OCORRENDO_MANUTENCAO 6
//

// EVENTOS
#define NENHUM_EVENTO -1
#define DETECTOU_MOEDA_ENTRANDO  0      
#define USUARIO_SUBMIT_DINHEIRO_INSERIDO 1    
#define USUARIO_TECLA_PRODUTO 2
#define COMPRA_VALIDA 3
#define COMPRA_INVALIDA 4
#define USUARIO_CANCELA_COMPRA 5
#define TIMER_FINALIZADO 6
#define TECLADO_MANUTENCAO_SUBMIT_SENHA_INSERIDA 7
#define SENHA_INVALIDA 8
#define SENHA_VALIDA 9
#define PORTA_DE_MANUTENCAO_FOI_FECHADA 10 
#define TECLADO_INTERNO_SUBMIT_CADASTRO_TROCO_EFETUADO 11
#define TECLADO_INTERNO_SUBMIT_CADASTRO_PRODUTO_EFETUADO 12


// ACOES
#define NENHUMA_ACAO -1
#define APOS_USUARIO_SUBMIT_DINHEIRO_INSERIDO 0
#define APOS_USUARIO_TECLA_PRODUTO 1
#define APOS_COMPRA_VALIDA 2
#define APOS_COMPRA_INVALIDA 3
#define APOS_USUARIO_CANCELA_COMPRA 4
#define APOS_TECLADO_MANUTENCAO_SUBMIT_SENHA_INSERIDA 5
#define APOS_SENHA_VALIDA 6
#define APOS_PORTA_DE_MANUTENCAO_FOI_FECHADA 7
#define APOS_TECLADO_INTERNO_SUBMIT_CADASTRO_TROCO_EFETUADO 8
#define APOS_TECLADO_INTERNO_SUBMIT_CADASTRO_PRODUTO_EFETUADO 9

#endif // DEFINICOES_SISTEMA_H_INCLUDED
